export const ALL_LANGUAGES: { [key: string]: string } = {
  "Abkhazian": "ab",
  "Afar": "aa",
  "Afrikaans": "af",
  "Akan": "ak",
  "Albanian": "sq",
  "Algerian Arabic": "ar-DZ",
  "Amharic": "am",
  "American English": "en-US",
  "American Spanish": "es-US",
  "Andorran Catalan": "ca-AD",
  "Aragonese": "an",
  "Arabic": "ar",
  "Argentine Spanish": "es-AR",
  "Armenian": "hy",
  "Assamese": "as",
  "Australian English": "en-AU",
  "Austrian German": "de-AT",
  "Azerbaijani": "az",
  "Azerbaijani (Cyrillic script)": "az-Cyrl",
  "Azerbaijani (Latin script)": "az-Latn",
  "Bahraini Arabic": "ar-BH",
  "Bambara": "bm",
  "Bambara (N'Ko script)": "bm-Nkoo",
  "Bashkir": "ba",
  "Basque": "eu",
  "Belarusian": "be",
  "Belarusian (Taraškievica orthography)": "be-tarask",
  "Belgian French": "fr-BE",
  "Belgian German": "de-BE",
  "Bengali": "bn",
  "Bosnian": "bs",
  "Bosnian (Cyrillic script)": "bs-Cyrl",
  "Bosnian (Latin script)": "bs-Latn",
  "Brazilian Portuguese": "pt-BR",
  "Breton": "br",
  "British English": "en-GB",
  "Bulgarian": "bg",
  "Bulgarian (Bulgaria)": "bg-BG",
  "Burmese": "my",
  "Canadian English": "en-CA",
  "Canadian French": "fr-CA",
  "Castilian Spanish (Spain)": "es-ES",
  "Catalan": "ca",
  "Central Khmer": "km",
  "Chadian Arabic": "ar-TD",
  "Chechen": "ce",
  "Chilean Spanish": "es-CL",
  "Chinese": "zh",
  "Chuvash": "cv",
  "Colombian Spanish": "es-CO",
  "Comorian Arabic": "ar-KM",
  "Cornish": "kw",
  "Corsican": "co",
  "Croatian": "hr",
  "Cypriot Greek": "el-CY",
  "Czech": "cs",
  "Czech (Czech Republic)": "cs-CZ",
  "Danish": "da",
  "Danish (Denmark)": "da-DK",
  "Dari (Afghan Persian)": "fa-AF",
  "Divehi (Maldivian)": "dv",
  "Djiboutian Afar": "aa-DJ",
  "Djiboutian Arabic": "ar-DJ",
  "Dutch": "nl",
  "Dzongkha": "dz",
  "Egyptian Arabic": "ar-EG",
  "Emirati Arabic": "ar-AE",
  "English": "en",
  "Eritrean Afar": "aa-ER",
  "Eritrean Arabic": "ar-ER",
  "Esperanto": "eo",
  "Estonian": "et",
  "Estonian (Estonia)": "et-EE",
  "European Portuguese": "pt-PT",
  "Ewe": "ee",
  "Faroese": "fo",
  "Filipino (Philippines)": "fil-PH",
  "Finnish": "fi",
  "Finnish (Finland)": "fi-FI",
  "French": "fr",
  "French Catalan": "ca-FR",
  "Fulah": "ff",
  "Fulah (Adlam script)": "ff-Adlm",
  "Fulah (Latin script)": "ff-Latn",
  "Galician": "gl",
  "Ganda": "lg",
  "Georgian": "ka",
  "German": "de",
  "Greek": "el",
  "Greenlandic Danish": "da-GL",
  "Guarani": "gn",
  "Gujarati": "gu",
  "Haitian Creole": "ht",
  "Hausa": "ha",
  "Hausa (Arabic script)": "ha-Arab",
  "Hebrew": "he",
  "Hebrew (Israel)": "he-IL",
  "Hindi": "hi",
  "Hindi (Latin script)": "hi-Latn",
  "Hungarian": "hu",
  "Icelandic": "is",
  "Ido": "io",
  "Igbo": "ig",
  "Indian Bengali": "bn-IN",
  "Indian English": "en-IN",
  "Indian Gujarati": "gu-IN",
  "Indian Hindi": "hi-IN",
  "Indonesian": "id",
  "Indonesian (Indonesia)": "id-ID",
  "Interlingua": "ia",
  "Interlingue": "ie",
  "Inuktitut": "iu",
  "Inuktitut (Latin script)": "iu-Latn",
  "Inupiaq": "ik",
  "Iranian Persian": "fa-IR",
  "Iraqi Arabic": "ar-IQ",
  "Iraqi Azerbaijani (Arabic script)": "az-Arab-IQ",
  "Irish": "ga",
  "Italian": "it",
  "Italian (Italy)": "it-IT",
  "Italian Catalan (Algherese)": "ca-IT",
  "Italian German": "de-IT",
  "Japanese": "ja",
  "Japanese (Japan)": "ja-JP",
  "Javanese": "jv",
  "Jordanian Arabic": "ar-JO",
  "Kalaallisut": "kl",
  "Kannada": "kn",
  "Kashmiri": "ks",
  "Kashmiri (Arabic script)": "ks-Arab",
  "Kashmiri (Devanagari script)": "ks-Deva",
  "Kazakh": "kk",
  "Kikuyu": "ki",
  "Kinyarwanda": "rw",
  "Korean": "ko",
  "Kurdish": "ku",
  "Kuwaiti Arabic": "ar-KW",
  "Kyrgyz": "ky",
  "Lao": "lo",
  "Latin": "la",
  "Latvian": "lv",
  "Lebanese Arabic": "ar-LB",
  "Libyan Arabic": "ar-LY",
  "Liechtenstein German": "de-LI",
  "Lingala": "ln",
  "Lithuanian": "lt",
  "Luba-Katanga": "lu",
  "Luxembourgish": "lb",
  "Luxembourgish German": "de-LU",
  "Macedonian": "mk",
  "Malagasy": "mg",
  "Malay": "ms",
  "Malayalam": "ml",
  "Maltese": "mt",
  "Manx": "gv",
  "Maori": "mi",
  "Marathi": "mr",
  "Mauritanian Arabic": "ar-MR",
  "Mexican Spanish": "es-MX",
  "Mongolian": "mn",
  "Moroccan Arabic": "ar-MA",
  "Moroccan French": "fr-MA",
  "Namibian Afrikaans": "af-NA",
  "Navajo": "nv",
  "Nepali": "ne",
  "New Zealand English": "en-NZ",
  "North Ndebele": "nd",
  "Northern Sami": "se",
  "Norwegian": "no",
  "Norwegian Bokmål": "nb",
  "Norwegian Nynorsk": "nn",
  "Occitan": "oc",
  "Omani Arabic": "ar-OM",
  "Oriya": "or",
  "Oromo": "om",
  "Ossetian": "os",
  "Palestinian Arabic": "ar-PS",
  "Palestinian Arabic (Israel)": "ar-IL",
  "Pashto": "ps",
  "Persian (Farsi)": "fa",
  "Peruvian Spanish": "es-PE",
  "Polish": "pl",
  "Polytonic Greek": "el-polyton",
  "Portuguese": "pt",
  "Punjabi": "pa",
  "Qatari Arabic": "ar-QA",
  "Quechua": "qu",
  "Romanian": "ro",
  "Romansh": "rm",
  "Rundi": "rn",
  "Russian": "ru",
  "Sango": "sg",
  "Sanskrit": "sa",
  "Sardinian": "sc",
  "Saudi Arabic": "ar-SA",
  "Scottish Gaelic": "gd",
  "Serbian": "sr",
  "Shona": "sn",
  "Sichuan Yi": "ii",
  "Simplified Chinese": "zh-Hans",
  "Sindhi": "sd",
  "Sinhala": "si",
  "Slovak": "sk",
  "Slovenian": "sl",
  "Somali": "so",
  "Somali Arabic": "ar-SO",
  "South African English": "en-ZA",
  "South Azerbaijani (Arabic script)": "az-Arab",
  "South Korean": "ko-KR",
  "South Ndebele": "nr",
  "South Sudanese Arabic": "ar-SS",
  "Southern Sotho": "st",
  "Spanish": "es",
  "Spanish Catalan": "ca-ES",
  "Standard French (France)": "fr-FR",
  "Standard German (Germany)": "de-DE",
  "Standard Greek (Greece)": "el-GR",
  "Sudanese Arabic": "ar-SD",
  "Sundanese": "su",
  "Swahili": "sw",
  "Swati": "ss",
  "Swedish": "sv",
  "Swiss French": "fr-CH",
  "Swiss German": "de-CH",
  "Syrian Arabic": "ar-SY",
  "Tagalog": "tl",
  "Tajik": "tg",
  "Tamil": "ta",
  "Tatar": "tt",
  "Telugu": "te",
  "Thai": "th",
  "Tibetan": "bo",
  "Tibetan (India)": "bo-IN",
  "Tigrinya": "ti",
  "Togolese Ewe": "ee-TG",
  "Tonga": "to",
  "Traditional Chinese": "zh-Hant",
  "Tsonga": "ts",
  "Tswana": "tn",
  "Tunisian Arabic": "ar-TN",
  "Turkish": "tr",
  "Turkish Azerbaijani (Arabic script)": "az-Arab-TR",
  "Turkmen": "tk",
  "Ukrainian": "uk",
  "Urdu": "ur",
  "Uyghur": "ug",
  "Uzbek": "uz",
  "Venda": "ve",
  "Vietnamese": "vi",
  "Volapük": "vo",
  "Walloon": "wa",
  "Welsh": "cy",
  "Western Frisian": "fy",
  "Western Saharan Arabic": "ar-EH",
  "Wolof": "wo",
  "Xhosa": "xh",
  "Yemeni Arabic": "ar-YE",
  "Yiddish": "yi",
  "Yoruba": "yo",
  "Zulu": "zu"
}
